# Generated by Django 5.0.6 on 2024-06-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0002_variacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
