# Generated by Django 5.0.6 on 2024-06-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0003_alter_produto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="produto_imagens/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing",
            field=models.FloatField(verbose_name="Preço"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing_promocional",
            field=models.FloatField(default=0, verbose_name="Preço Promo."),
        ),
    ]
